# Generated by Django 2.1.8 on 2019-10-07 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('about_id', models.AutoField(primary_key=True, serialize=False)),
                ('about_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('about_name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('Icon', models.ImageField(blank=True, null=True, upload_to='photo/')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('category_name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField()),
                ('order', models.IntegerField()),
                ('Icon', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('main_category_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name_en', models.CharField(max_length=255)),
                ('company_name_ar', models.CharField(max_length=255)),
                ('address_en', models.CharField(max_length=255, null=True)),
                ('address_ar', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True)),
                ('Facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('google_business', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('short_description', models.TextField(blank=True, null=True)),
                ('keywords_en', models.TextField(blank=True, null=True)),
                ('keywords_ar', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('product_description_en', models.CharField(blank=True, max_length=255, null=True)),
                ('short_desc_en', models.CharField(blank=True, max_length=255, null=True)),
                ('short_desc_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('product_description_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('old_price', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField()),
                ('order', models.IntegerField()),
                ('new_arrival', models.BooleanField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='sales_order',
            fields=[
                ('sales_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_num', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(blank=True)),
                ('full_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('service_name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('service_icon', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('status', models.BooleanField()),
                ('service_desc_en', models.CharField(blank=True, max_length=255, null=True)),
                ('service_desc_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('slider_id', models.AutoField(primary_key=True, serialize=False)),
                ('slider_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('slider_name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('slider_description_en', models.TextField(blank=True, null=True)),
                ('slider_description_ar', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='photo/')),
            ],
        ),
    ]
